name: ROM Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run build script
      env:
        ROMS_AWS_ACCESS_KEY: ${{ secrets.ROMS_AWS_ACCESS_KEY }}
        ROMS_AWS_SECRET_ACCESS_KEY: ${{ secrets.ROMS_AWS_SECRET_ACCESS_KEY }}
      run: node build.js
    
    - name: Commit generated roms.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "CI Build roms.json"
        git config user.email sojscoder@gmail.com
        git add roms.json
        git commit -m "Update roms.json [skip ci]" || exit 0
        git push
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages,
        exclude_assets: '.github,package.json,static.js,build.js,rename.js,README.md',
        force_orphan: true